name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.24
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test_outbox
      postgres:
        image: postgres:13.2-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: test_outbox
      rabbit:
        image: 'rabbitmq:3.8.9-management-alpine'
        ports:
          - "5672:5672"
      sqs:
        image: 'localstack/localstack'
        ports:
          - "4566:4566"
        env:
          SERVICES: sqs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -race ./...
        env:
          MINE_INTERVAL: 1s
          MYSQL_URI: user:password@tcp(localhost:3306)/test_outbox
          PG_URI: postgres://postgres:password@localhost:5432/test_outbox?sslmode=disable
          RABBITMQ_URI: amqp://guest:guest@localhost:5672
          SQS_URI: http://localhost:4566
